# syntax=docker/dockerfile:1
FROM python:3.8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY ./order_accept/ /code/order_accept/
WORKDIR /code/order_accept/
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]